#+TITLE: Social Networks and Privacy Models
#+AUTHOR: Clarissa Littler

* Introduction
** The Problem
   Handling privacy and control over content is still an open problem for social media.

   Currently, for any of the major social networks, the more you make full use of social media the more you open yourself up to interactions you don't want: people you don't want to talk to are responding to your words, you're being dragged into conversations you don't want to have, people missing the point with their comments on your work or stripping away attributions from art. 

   Stories of harassment on social media are common place. Not only are conversations regularly, rudely, interrupted but if a post "goes viral" and is quickly spread, then the post's author almost always faces some kind of social consequences. Whether it's several hundred or thousand people not getting the joke and sending variants of the same angry message or it's targeted harassment for an unpopular opinion, the more people who see a post the more potential danger there is for the creator of the post.

   Now, one might be tempted to rebut that these conversations are happening on the public internet and are, thus, fair game for anyone who sees them, but I think that's a rather limiting notion of human interaction. After all, we have expectations of privacy even in offline public places. You don't expect random people to start arguments with you when you're sitting and speaking quietly with a friend, no matter how many people you know or how much social influence you have. 

   I don't think that we should give up our social rules and politeness and respect for each other because it's a new form of communication. In fact, I'd argue the opposite: we need to find better ways to express and enforce how we want to interact with each other. 
   
   Exploring how to do that is going to be the bulk of this note, but first we need to discuss the current state of things.
** Surveying the Field
   For the purpose of this note, we'll be discussing just Facebook, Twitter, and Tumblr as examples of social networks. Not just because these are the ones I'm most familiar with, but also because they're the most popular general-purpose social networks. By general purpose I mean there is a variety of content types and modes of interaction with the site, as opposed to something like Instagram or Vine which is much more special focused on one kind of content and interaction.

   First, we'll discuss the privacy of Facebook. Facebook probably has the most flexible privacy of the three networks we'll be discussing. You can set custom filters on a per-post basis and there's built in tiers of friends, friends-of-friends, and public. In general, though, these filters are about who can *see* a post and there's no distinctions over what types of interactions someone is allowed if they can see the post. Visibility, in a sense, grants all possible permissions on the content.

   Twitter is, by comparison, very very limited in its privacy model. You can block an individual or you can lock down your account so it is only viewable by your followers and you must manually approve requests to follow you. This is a very all-or-nothing idea of privacy: either you are whispering in a private residence or you are making public challenges at a free-for-all debate, neither of which are particularly natural modes of interaction.

   Tumblr is similar to Twitter in this regard. You can make your blog password protected, you can block, and you can make your blog viewable only on someone else's dash and not by directly visiting your blog's URL. Again, these are fairly all-or-nothing approaches to privacy. If someone can see a post then they can interact with it in any possible way.

** An Outline
   For the rest of this note, we'll be addressing one attempt at addressing these issues of privacy in social media. We'll start by layout out, from real life situations, the kinds of expectations of privacy we'd want to have. Then we'll be trying to semi-rigorously lay out all the different forms of interaction we might want to have in social media, teasing apart some separate concepts that I think are conflated in existing systems.

   Then we'll be describing the idea of "permissions" in relation to social media and interaction with content and how fine grained separation of permissions might help improve our networks.

   After that, we'll discuss the notion of capabilities in operating systems and how a concept very much like capabilities can help guide us in understanding how to view privacy on a per-post basis and how to control information flow. 

   Finally, we'll discuss what this hypothetical social network will look like by going through a series of use cases.
* In-person Interactions
  In this section we'll be talking about a number of examples of social interactions that occur in person and discussing the ideas of privacy in interactions that are relevant. I don't intend to classify the gamut of human interaction, but just the ones that seem relevant to our experience of social media. 
** Examples
*** Restaurant
    Imagine being in a restaurant, talking with your friends at your own table. You don't expect anyone to come up to your table and talk to you. You wouldn't expect someone to invite themselves to sit at your table and participate on this time together. 

    By the standards people often use to describe the internet, you should expect those things! After all, you're in public and public means a free-for-all. Of course, that's obviously not true about our in person interactions. In the restaurant example, there's a sense of privacy and expectation that others are excluded from participating. You know full well that people may *listen* to your conversations. I can't really stop my ability to hear all the conversations going on around me in a public place, but I'm never even tempted to invite myself to join in because it's simply understood that that's rude: it violates expectation of privacy.

    In terms of social media, this is the equivalent of being able to witness a conversation but not participate in it. That's a mode of interaction that no current social network can really support. The closest example would be when you can witness Facebook friends commenting on other people's posts from the sidebar. You can't *set* conversations in Facebook to be public-but-exclusive. 
*** Hack night
    Imagine being at a hack night. You're at a venue with large tables and everyone has set up with their laptops and drinks of choice. Nothing organized is happening, just people working on their individual projects and chatting. You're talking with a friend about your newest pet project when someone else at your table perks up and joins the conversation because it's a topic they love too.

    Is that an odd occurence? Would it be unexpected? In this situation, not really. It's expected that other people would want to join in conversations that are relevant to their interests. In the context of a hackathon or the like, part of the goal is to connect with people interested in similar things.
** Social Contracts
   In this section, I won't be presenting any sort of grand philosophic or sociologic thesis, but I want to somewhat informall use the idea of a social contract to discuss why online interactions play by  
* Online Interactions 
** Scope
** Scale
* Separating Permissions
** Permissions in Operating Systems 
** Permissions in Social Media
* Capabilities
** In Operating Systems
** Posts as Capabilities
* A Rough Design

